### PR TITLE
Updated `actix_web` to stable version and fixed imports

### PR DESCRIPTION
**Pull request by Bricklou**
The stable version of `actix_web@4` has been released yesterday, here is a PR to update the cargo deps version and fix an import error

### CODE REVIEW

**Comment by shaaraddalvi** [comment]
This PR is required to build the crate successfully

**Comment by redvg** [comment]
can you merge that pls?

**Comment by PiyushXCoder** [comment]
Merged

**Comment by PiyushXCoder** [comment]
Hey sorry for late reply. Suggest me if anyone have a good android app for Github or if anyone wanna contribute on this project.

**Comment by Bricklou** [comment]
> Hey sorry for late reply. Suggest me if anyone have a good android app for Github or if anyone wanna contribute on this project.
 @PiyushXCoder

GitHub has now an official app named "GitHub Mobile": https://github.com/mobile/

**Comment by PiyushXCoder** [comment]
Thanks, I really needed it.

**Comment by Bricklou** [comment]
And it seems the original repos now support actix 4: https://github.com/rambler-digital-solutions/actix-web-validator/blob/ca9688b4d0de5e0ed27b723f7792b8ef89687d9f/Cargo.toml#L15-L16

**Comment by PiyushXCoder** [comment]
Yes that is a great news. This repo was just an temporary shift for testing while actix 4 was in beta

**Pull request merged**
